pipeline {
    agent any

    tools {
        nodejs 'nodejs 18.13.0'
    }

    stages {
        stage('BUILD') {
            when { changeset "**/frontend/**" }
            steps {
		        sh "chmod +x -R ${env.WORKSPACE}"
                sh './pipeline/jenkins/frontend/build/build.sh'
            }
        }

	    stage('DEPLOY') {
            when { changeset "**/frontend/**" }
            steps {
                sh "chmod +x -R ${env.WORKSPACE}"
                sh './pipeline/jenkins/frontend/deploy/deploy.sh'
            }
        }

    }
}
