pipeline {
    agent any
    stages {
        stage('BUILD') {
            steps {
		sh "chmod +x -R ${env.WORKSPACE}"
                sh './pipeline/jenkins/build/build.sh'
            }
        }
	stage('DEPLOY') {
            steps {
                sh "chmod +x -R ${env.WORKSPACE}"
                sh './pipeline/jenkins/deploy/deploy.sh'
            }
        }

    }
}
