pipeline {
    agent any
    stages {
        stage('BUILD') {
            steps {
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
								echo "Workspace is ${env.WORKSPACE}"
            }
        }
    }
}
