node {
  stage('SCM') {
    checkout scm
  }
  env.NODEJS_HOME = "${tool 'nodejs 18.13.0'}"
    // on linux / mac
  env.PATH="${env.NODEJS_HOME}/bin:${env.PATH}"
  stage('SonarQube Analysis') {
    def scannerHome = tool 'SonarScanner';
    withSonarQubeEnv() {
      sh "${scannerHome}/bin/sonar-scanner"
    }
  }
}
