pipeline {
    agent any

    tools {
        gradle 'gradle 7.6.1'
    }

    stages {
        stage('BUILD') {
            steps {
		sh "chmod +x -R ${env.WORKSPACE}"
                sh './pipeline/jenkins/backend/build/build.sh'
            }
        }
	stage('DEPLOY') {
            steps {
                sh "chmod +x -R ${env.WORKSPACE}"
                sh './pipeline/jenkins/backend/deploy/deploy.sh'
            }
        }

    }
}
